#!/bin/bash

#add to the stage
git add .

while [[ "${answer}" != "yes" ]]
do
	echo -ne "\e[35myour commit please: \e[00m\e[32m"
	read commit
	echo -e "\e[00m"
	echo -ne "\n\e[30;44mare you sure?\e[00m \e[35myour commit: \e[00m \"${commit}\"\n\n\e[00;36m[YES/NO]: \e[32m"
	read answer
	echo -ne "\e[00m"
done

git commit -m "${commit}"
git push
